name: Workflow Triggered From Remote
on:
  repository_dispatch:
    types: [TriggerRemoteRepoEvent]
jobs:
  receiveDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Echo dispatch message
        run: |
          echo event triggered.