name: Workflow Triggered From Remote
on:
  repository_dispatch:
    types: [TriggerRemoteRepoEvent]
jobs:
  receiveDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
