name: Workflow Triggered From Remote
on:
  repository_dispatch:
    types: [TriggerRemoteRepoEvent]
jobs:
  receiveDispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Echo dispatch message
        run: echo "event triggered."
      - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '30s'
      - run: echo "sleep is over"