name: repoBworkflow
on:
  repository_dispatch:
    types: [RepoAevent]
jobs:
  repoBjobs:
    runs-on: ubuntu-latest
    steps:
      - name: testB
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."